In [79]:
import pandas as pd

dataSetA = pd.read_csv('world.csv')
dataSetB = pd.read_csv('vacs.csv')
dataSetC = pd.read_csv('earthquake_1995-2023.csv')

# selected_columns = df.loc[:, ['Column1', 'Column2', 'Column3']]

dataSetCfiltered = dataSetC.loc[:, ['magnitude', 'date_time', 'country']]
dataSetCfiltered_by_country = dataSetCfiltered.groupby(['country'])['magnitude'].max()
dataSetA.columns = dataSetA.columns.str.upper()
dataSetB.columns = dataSetB.columns.str.upper()

# Merge the DataFrames based on the 'Country' column

merged_data = pd.merge(dataSetA, dataSetB, on='COUNTRY')
merged_data2 = pd.merge(dataSetCfiltered, dataSetCfiltered_by_country, on='country')
merged_data3 = merged_data2.drop_duplicates(subset = ['country'])
dataSetCfiltered_by_country.head()
merged_data4 = merged_data3.drop('magnitude_x', axis=1)
merged_data4.columns = merged_data4.columns.str.upper()

merge_data5 = pd.merge(dataSetA, merged_data4, on='COUNTRY')
merge_data5.head()

,COUNTRY,DENSITY\n(P/KM2),ABBREVIATION,AGRICULTURAL LAND( %),LAND AREA(KM2),ARMED FORCES SIZE,BIRTH RATE,CALLING CODE,CAPITAL/MAJOR CITY,CO2-EMISSIONS,CPI,CPI CHANGE (%),CURRENCY-CODE,FERTILITY RATE,FORESTED AREA (%),GASOLINE PRICE,GDP,GROSS PRIMARY EDUCATION ENROLLMENT (%),GROSS TERTIARY EDUCATION ENROLLMENT (%),INFANT MORTALITY,LARGEST CITY,LIFE EXPECTANCY,MATERNAL MORTALITY RATIO,MINIMUM WAGE,OFFICIAL LANGUAGE,OUT OF POCKET HEALTH EXPENDITURE,PHYSICIANS PER THOUSAND,POPULATION,POPULATION: LABOR FORCE PARTICIPATION (%),TAX REVENUE (%),TOTAL TAX RATE,UNEMPLOYMENT RATE,URBAN_POPULATION,LATITUDE,LONGITUDE,DATE_TIME,MAGNITUDE_Y
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953,21-03-2023 16:47,7.5
1,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626,21-05-2003 18:44,6.8
2,Argentina,17,AR,54.30%,"2,780,400","105,000",17.02,54.0,Buenos Aires,"201,348",232.75,53.50%,ARS,2.26,9.80%,$1.10,"$449,663,446,954",109.70%,90.00%,8.8,Buenos Aires,76.5,39.0,$3.35,Spanish,17.60%,3.96,"44,938,712",61.30%,10.10%,106.30%,9.79%,"41,339,571",-38.416097,-63.616672,17-07-2023 03:05,7.2
3,Azerbaijan,123,AZ,57.70%,"86,600","82,000",14.00,994.0,Baku,"37,620",156.32,2.60%,AZN,1.73,14.10%,$0.56,"$39,207,000,000",99.70%,27.70%,19.2,Baku,72.9,26.0,$0.47,Azerbaijani language,78.60%,3.45,"10,023,318",66.50%,13.00%,40.70%,5.51%,"5,616,165",40.143105,47.576927,25-11-2000 18:10,6.8
4,Bolivia,11,BO,34.80%,"1,098,581","71,000",21.75,591.0,Sucre,"21,606",148.32,1.80%,BOB,2.73,50.30%,$0.71,"$40,895,322,865",98.20%,NaN,21.8,Santa Cruz de la Sierra,71.2,155.0,$1.36,Spanish,25.90%,1.59,"11,513,100",71.80%,17.00%,83.70%,3.50%,"8,033,035",-16.290154,-63.588653,02-04-2018 13:40,6.8

In [80]:
m5_filtered = merge_data5.drop(['LONGITUDE', 'LATITUDE', 'CURRENCY-CODE','ABBREVIATION', 'LARGEST CITY','CALLING CODE','CAPITAL/MAJOR CITY','GROSS TERTIARY EDUCATION ENROLLMENT (%)'], axis = 1)

In [81]:
m5_filtered = m5_filtered.dropna()
m5_filtered.head()

,COUNTRY,DENSITY\n(P/KM2),AGRICULTURAL LAND( %),LAND AREA(KM2),ARMED FORCES SIZE,BIRTH RATE,CO2-EMISSIONS,CPI,CPI CHANGE (%),FERTILITY RATE,FORESTED AREA (%),GASOLINE PRICE,GDP,GROSS PRIMARY EDUCATION ENROLLMENT (%),INFANT MORTALITY,LIFE EXPECTANCY,MATERNAL MORTALITY RATIO,MINIMUM WAGE,OFFICIAL LANGUAGE,OUT OF POCKET HEALTH EXPENDITURE,PHYSICIANS PER THOUSAND,POPULATION,POPULATION: LABOR FORCE PARTICIPATION (%),TAX REVENUE (%),TOTAL TAX RATE,UNEMPLOYMENT RATE,URBAN_POPULATION,DATE_TIME,MAGNITUDE_Y
0,Afghanistan,60,58.10%,"652,230","323,000",32.49,"8,672",149.9,2.30%,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,47.9,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",21-03-2023 16:47,7.5
1,Algeria,18,17.40%,"2,381,741","317,000",24.28,"150,006",151.36,2.00%,3.02,0.80%,$0.28,"$169,988,236,398",109.90%,20.1,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",21-05-2003 18:44,6.8
2,Argentina,17,54.30%,"2,780,400","105,000",17.02,"201,348",232.75,53.50%,2.26,9.80%,$1.10,"$449,663,446,954",109.70%,8.8,76.5,39.0,$3.35,Spanish,17.60%,3.96,"44,938,712",61.30%,10.10%,106.30%,9.79%,"41,339,571",17-07-2023 03:05,7.2
3,Azerbaijan,123,57.70%,"86,600","82,000",14.00,"37,620",156.32,2.60%,1.73,14.10%,$0.56,"$39,207,000,000",99.70%,19.2,72.9,26.0,$0.47,Azerbaijani language,78.60%,3.45,"10,023,318",66.50%,13.00%,40.70%,5.51%,"5,616,165",25-11-2000 18:10,6.8
4,Bolivia,11,34.80%,"1,098,581","71,000",21.75,"21,606",148.32,1.80%,2.73,50.30%,$0.71,"$40,895,322,865",98.20%,21.8,71.2,155.0,$1.36,Spanish,25.90%,1.59,"11,513,100",71.80%,17.00%,83.70%,3.50%,"8,033,035",02-04-2018 13:40,6.8

In [82]:
pd.set_option('display.max_columns', None)
m5_filtered.head()

,COUNTRY,DENSITY\n(P/KM2),AGRICULTURAL LAND( %),LAND AREA(KM2),ARMED FORCES SIZE,BIRTH RATE,CO2-EMISSIONS,CPI,CPI CHANGE (%),FERTILITY RATE,FORESTED AREA (%),GASOLINE PRICE,GDP,GROSS PRIMARY EDUCATION ENROLLMENT (%),INFANT MORTALITY,LIFE EXPECTANCY,MATERNAL MORTALITY RATIO,MINIMUM WAGE,OFFICIAL LANGUAGE,OUT OF POCKET HEALTH EXPENDITURE,PHYSICIANS PER THOUSAND,POPULATION,POPULATION: LABOR FORCE PARTICIPATION (%),TAX REVENUE (%),TOTAL TAX RATE,UNEMPLOYMENT RATE,URBAN_POPULATION,DATE_TIME,MAGNITUDE_Y
0,Afghanistan,60,58.10%,"652,230","323,000",32.49,"8,672",149.9,2.30%,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,47.9,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",21-03-2023 16:47,7.5
1,Algeria,18,17.40%,"2,381,741","317,000",24.28,"150,006",151.36,2.00%,3.02,0.80%,$0.28,"$169,988,236,398",109.90%,20.1,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",21-05-2003 18:44,6.8
2,Argentina,17,54.30%,"2,780,400","105,000",17.02,"201,348",232.75,53.50%,2.26,9.80%,$1.10,"$449,663,446,954",109.70%,8.8,76.5,39.0,$3.35,Spanish,17.60%,3.96,"44,938,712",61.30%,10.10%,106.30%,9.79%,"41,339,571",17-07-2023 03:05,7.2
3,Azerbaijan,123,57.70%,"86,600","82,000",14.00,"37,620",156.32,2.60%,1.73,14.10%,$0.56,"$39,207,000,000",99.70%,19.2,72.9,26.0,$0.47,Azerbaijani language,78.60%,3.45,"10,023,318",66.50%,13.00%,40.70%,5.51%,"5,616,165",25-11-2000 18:10,6.8
4,Bolivia,11,34.80%,"1,098,581","71,000",21.75,"21,606",148.32,1.80%,2.73,50.30%,$0.71,"$40,895,322,865",98.20%,21.8,71.2,155.0,$1.36,Spanish,25.90%,1.59,"11,513,100",71.80%,17.00%,83.70%,3.50%,"8,033,035",02-04-2018 13:40,6.8

In [83]:
m5_filtered.size

1015

In [84]:
data = m5_filtered

In [85]:
whr = pd.read_csv("WHR2023.csv")
whr.head()

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.804,0.036,7.875,7.733,10.792,0.969,71.150,0.961,-0.019,0.182,1.778,1.888,1.585,0.535,0.772,0.126,0.535,2.363
1,Denmark,7.586,0.041,7.667,7.506,10.962,0.954,71.250,0.934,0.134,0.196,1.778,1.949,1.548,0.537,0.734,0.208,0.525,2.084
2,Iceland,7.530,0.049,7.625,7.434,10.896,0.983,72.050,0.936,0.211,0.668,1.778,1.926,1.620,0.559,0.738,0.250,0.187,2.250
3,Israel,7.473,0.032,7.535,7.411,10.639,0.943,72.697,0.809,-0.023,0.708,1.778,1.833,1.521,0.577,0.569,0.124,0.158,2.691
4,Netherlands,7.403,0.029,7.460,7.346,10.942,0.930,71.550,0.887,0.213,0.379,1.778,1.942,1.488,0.545,0.672,0.251,0.394,2.110

In [86]:
labels = ['Very Low', 'Low', 'Moderate', 'High', 'Very High']
levels = [1,2,3,4,5]
whr['Level Of Corruption'] = pd.cut(whr['Perceptions of corruption'], bins=5, labels = labels)
whr['Level Of Social Support in Society'] = pd.cut(whr['Social support'], bins=5, labels = labels)
whr['Generosity'] = pd.cut(whr['Generosity'], bins=5, labels = levels)
whr['Freedom to make life choices'] = pd.cut(whr['Freedom to make life choices'], bins=5, labels = levels)
whr['Ladder score'] = pd.cut(whr['Ladder score'], bins=5, labels = levels)

In [87]:
whr['COUNTRY'] = whr['Country name']
whr_filtered = whr[['COUNTRY', 'Generosity','Ladder score', 'Freedom to make life choices', 'Level Of Social Support in Society', 'Level Of Corruption']] 
whr_filtered.head()

,COUNTRY,Generosity,Ladder score,Freedom to make life choices,Level Of Social Support in Society,Level Of Corruption
0,Finland,2,5,5,Very High,Very Low
1,Denmark,3,5,5,Very High,Very Low
2,Iceland,3,5,5,Very High,High
3,Israel,2,5,4,Very High,High
4,Netherlands,3,5,5,Very High,Low

In [88]:

data = pd.merge(data, whr_filtered, on='COUNTRY')

In [89]:
data.head()

,COUNTRY,DENSITY\n(P/KM2),AGRICULTURAL LAND( %),LAND AREA(KM2),ARMED FORCES SIZE,BIRTH RATE,CO2-EMISSIONS,CPI,CPI CHANGE (%),FERTILITY RATE,FORESTED AREA (%),GASOLINE PRICE,GDP,GROSS PRIMARY EDUCATION ENROLLMENT (%),INFANT MORTALITY,LIFE EXPECTANCY,MATERNAL MORTALITY RATIO,MINIMUM WAGE,OFFICIAL LANGUAGE,OUT OF POCKET HEALTH EXPENDITURE,PHYSICIANS PER THOUSAND,POPULATION,POPULATION: LABOR FORCE PARTICIPATION (%),TAX REVENUE (%),TOTAL TAX RATE,UNEMPLOYMENT RATE,URBAN_POPULATION,DATE_TIME,MAGNITUDE_Y,Generosity,Ladder score,Freedom to make life choices,Level Of Social Support in Society,Level Of Corruption
0,Afghanistan,60,58.10%,"652,230","323,000",32.49,"8,672",149.9,2.30%,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,47.9,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",21-03-2023 16:47,7.5,2,1,1,Very Low,Very High
1,Algeria,18,17.40%,"2,381,741","317,000",24.28,"150,006",151.36,2.00%,3.02,0.80%,$0.28,"$169,988,236,398",109.90%,20.1,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",21-05-2003 18:44,6.8,1,3,2,Very High,High
2,Argentina,17,54.30%,"2,780,400","105,000",17.02,"201,348",232.75,53.50%,2.26,9.80%,$1.10,"$449,663,446,954",109.70%,8.8,76.5,39.0,$3.35,Spanish,17.60%,3.96,"44,938,712",61.30%,10.10%,106.30%,9.79%,"41,339,571",17-07-2023 03:05,7.2,2,4,4,Very High,Very High
3,Bolivia,11,34.80%,"1,098,581","71,000",21.75,"21,606",148.32,1.80%,2.73,50.30%,$0.71,"$40,895,322,865",98.20%,21.8,71.2,155.0,$1.36,Spanish,25.90%,1.59,"11,513,100",71.80%,17.00%,83.70%,3.50%,"8,033,035",02-04-2018 13:40,6.8,2,4,5,High,Very High
4,Botswana,4,45.60%,"581,730","9,000",24.82,"6,340",149.75,2.80%,2.87,18.90%,$0.71,"$18,340,510,789",103.20%,30.0,69.3,144.0,$0.29,English,5.30%,0.37,"2,346,179",70.80%,19.50%,25.10%,18.19%,"1,616,550",03-04-2017 17:40,6.5,1,2,4,High,Very High

In [97]:
data['date'] = pd.to_datetime(data['DATE_TIME']).dt.date
data = data[['date', 'COUNTRY', 'DENSITY\n(P/KM2)', 'AGRICULTURAL LAND( %)', 'LAND AREA(KM2)', 'BIRTH RATE','CO2-EMISSIONS', 'FERTILITY RATE', 'FORESTED AREA (%)', 'GDP', 'INFANT MORTALITY',  'LIFE EXPECTANCY', 'MINIMUM WAGE', 'OFFICIAL LANGUAGE','PHYSICIANS PER THOUSAND', 'POPULATION', 'TOTAL TAX RATE', 'UNEMPLOYMENT RATE', 'Generosity', 'Ladder score','Freedom to make life choices', 'Level Of Social Support in Society', 'Level Of Corruption']]

/var/folders/rd/9nbcv3cs77b4zg8s993nhqrc0000gn/T/ipykernel_32686/3291473079.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['date'] = pd.to_datetime(data['DATE_TIME']).dt.date

In [98]:
data.head()

,date,COUNTRY,DENSITY\n(P/KM2),AGRICULTURAL LAND( %),LAND AREA(KM2),BIRTH RATE,CO2-EMISSIONS,FERTILITY RATE,FORESTED AREA (%),GDP,INFANT MORTALITY,LIFE EXPECTANCY,MINIMUM WAGE,OFFICIAL LANGUAGE,PHYSICIANS PER THOUSAND,POPULATION,TOTAL TAX RATE,UNEMPLOYMENT RATE,Generosity,Ladder score,Freedom to make life choices,Level Of Social Support in Society,Level Of Corruption
0,2023-03-21,Afghanistan,60,58.10%,"652,230",32.49,"8,672",4.47,2.10%,"$19,101,353,833",47.9,64.5,$0.43,Pashto,0.28,"38,041,754",71.40%,11.12%,2,1,1,Very Low,Very High
1,2003-05-21,Algeria,18,17.40%,"2,381,741",24.28,"150,006",3.02,0.80%,"$169,988,236,398",20.1,76.7,$0.95,Arabic,1.72,"43,053,054",66.10%,11.70%,1,3,2,Very High,High
2,2023-07-17,Argentina,17,54.30%,"2,780,400",17.02,"201,348",2.26,9.80%,"$449,663,446,954",8.8,76.5,$3.35,Spanish,3.96,"44,938,712",106.30%,9.79%,2,4,4,Very High,Very High
3,2018-04-02,Bolivia,11,34.80%,"1,098,581",21.75,"21,606",2.73,50.30%,"$40,895,322,865",21.8,71.2,$1.36,Spanish,1.59,"11,513,100",83.70%,3.50%,2,4,5,High,Very High
4,2017-04-03,Botswana,4,45.60%,"581,730",24.82,"6,340",2.87,18.90%,"$18,340,510,789",30.0,69.3,$0.29,English,0.37,"2,346,179",25.10%,18.19%,1,2,4,High,Very High

In [99]:
print(data.describe())

       BIRTH RATE  FERTILITY RATE  INFANT MORTALITY  LIFE EXPECTANCY  \
count   30.000000       30.000000         30.000000        30.000000
mean    20.453333        2.555333         20.410000        73.070000
std      7.480852        0.944639         14.693145         5.382228
min      8.100000        1.350000          3.600000        60.200000
25%     15.415000        1.837500          9.375000        69.900000
50%     18.515000        2.285000         16.300000        72.900000
75%     24.490000        2.892500         29.100000        76.500000
max     37.520000        4.890000         57.200000        81.900000

       PHYSICIANS PER THOUSAND
count                30.000000
mean                  1.753667
std                   1.335436
min                   0.010000
25%                   0.697500
50%                   1.585000
75%                   2.605000
max                   5.480000

In [108]:
data[['OFFICIAL LANGUAGE']].value_counts()

OFFICIAL LANGUAGE
Spanish              9
English              3
Arabic               2
Persian              2
Portuguese           2
Russian              2
Burmese              1
French               1
Greek                1
Hindi                1
Indonesian           1
Mongolian            1
Nepali               1
Pashto               1
Swahili              1
Urdu                 1
Name: count, dtype: int64

In [109]:
data[['Generosity']].value_counts()

Generosity
2             14
3              8
1              6
5              2
4              0
Name: count, dtype: int64

In [110]:
data[['Ladder score']].value_counts()

Ladder score
4               16
3                8
2                3
5                2
1                1
Name: count, dtype: int64

In [111]:
data[['Freedom to make life choices']].value_counts()

Freedom to make life choices
5                               13
4                               10
2                                3
3                                3
1                                1
Name: count, dtype: int64

In [112]:
data[['Level Of Social Support in Society']].value_counts()

Level Of Social Support in Society
High                                  15
Very High                             10
Moderate                               4
Very Low                               1
Low                                    0
Name: count, dtype: int64

In [113]:
data[['Level Of Corruption']].value_counts()

Level Of Corruption
Very High              16
High                   10
Moderate                2
Very Low                1
Low                     1
Name: count, dtype: int64